@UniShareProject.API_HostAddress = https://localhost:7150

POST {{UniShareProject.API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  
  "firstName": "test2",
  "lastName": "user2",
  "email": "test2.user2@principia.edu",
  "password": "Th1s1stest2"

}

###
